### ISSUE TITLE
0.4.0 regression: on_retry's type is now invalid under inference

### ISSUE THREAD

**Issue by teozkr** [EmbarkStudios/tryhard#20]
**Describe the bug**

`on_retry` now requires an unsatisfiable lifetime.

**To Reproduce**

Try to compile the following:

```rust
use std::convert::Infallible;
use tryhard::retry_fn;

fn main() {
    let _ = async {
        let _ = retry_fn(|| async { Result::<_, Infallible>::Ok(()) })
            .retries(0)
            .on_retry(|_, _, _| async {})
            .await;
    };
}
```

This fails to compile with the error message:

```
    Updating crates.io index
    Checking tryhard-on-retry-regression v0.1.0 (/home/teo/junk/tryhard-on-retry-regression)
error: implementation of `std::ops::FnOnce` is not general enough
 --> src/main.rs:6:17
  |
6 |           let _ = retry_fn(|| async { Result::<_, Infallible>::Ok(()) })
  |  _________________^
7 | |             .retries(0)
8 | |             .on_retry(|_, _, _| async {})
9 | |             .await;
  | |__________________^ implementation of `std::ops::FnOnce` is not general enough
  |
  = note: closure with signature `fn(u32, std::option::Option<std::time::Duration>, &'2 std::convert::Infallible) -> impl std::future::Future` must implement `std::ops::FnOnce<(u32, std::option::Option<std::time::Duration>, &'1 std::convert::Infallible)>`, for any lifetime `'1`...
  = note: ...but it actually implements `std::ops::FnOnce<(u32, std::option::Option<std::time::Duration>, &'2 std::convert::Infallible)>`, for some specific lifetime `'2`

error: aborting due to previous error

error: could not compile `tryhard-on-retry-regression`
```

**Expected behavior**
The code should compile successfully, like it did on 0.3.0.

**Device:**
 - OS: Arch Linux
 - rustc 1.53.0 (53cb7b09b 2021-06-17) via Rustup

**Comment by teozkr** [comment]
Curious, writing out error type explicitly works fine, so the following compiles just fine under both 0.4.0 and 0.3.0:

```rust
use std::convert::Infallible;
use tryhard::retry_fn;

fn main() {
    let _ = async {
        let _ = retry_fn(|| async { Ok(()) })
            .retries(0)
            .on_retry(|_, _, _: &Infallible| async {})
            .await;
    };
}
```

**Comment by davidpdrsn** [comment]
Yes, declaring the error type is also what I do. Not sure if there is a better solution.

**Comment by teozkr** [comment]
I'm mostly baffled by what on earth caused this regression, compared to 0.3.0 :/

**Comment by davidpdrsn** [comment]
I think its because I removed the trait bounds on [`RetryFuture::on_retry`](https://github.com/EmbarkStudios/tryhard/blob/main/src/lib.rs#L417). I removed them because `on_retry` previously only worked with closures. But in 0.4 that was expanded to work with anything that implements `OnRetry`.

It might be possible to bring the bounds back for `RetryFuture::on_retry` but I don't think its possible for `RetryFutureConfig::on_retry` since we haven't bound the error type at that point. One could make `RetryFutureConfig` have a `PhantomData<E>` but that introduces a bunch of other issues. So I removed the bounds from `RetryFuture::on_retry` so it was consistent with `RetryFutureConfig::on_retry`. I suppose the bounds could be re-introduced for `RetryFuture::on_retry` as that is probably used more often.

You're welcome to see if you can find a fix otherwise I might look into it within the coming weeks.
